spring:
  profiles:
    active:
      - prod

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}


paystack-secret-key: ${PAYSTACK_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

jwt:
  secret: ${JWT_SECRET}

server:
  error:
    include-message: always

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true


server:
  error:
    include-message: always

  port: ${PORT:5000}